#!/usr/bin/env python3
"""Generate the App-only read key without printing it or committing it."""
import json
import os
from pathlib import Path
import re
import sys


def main():
    key = os.environ.get("APP_RUNTIME_API_KEY", "").strip()
    archive = bool(os.environ.get("DEVELOPMENT_TEAM"))
    if archive and not key:
        sys.exit("Set LOTTERY_READ_API_KEY in this repository's Actions Secrets before TestFlight.")
    if key and not re.fullmatch(r"[A-Za-z0-9_-]{32,128}", key):
        sys.exit("LOTTERY_READ_API_KEY must be 32-128 URL-safe random characters.")
    value = json.dumps(key) if key else "nil"
    target = Path(__file__).resolve().parents[1] / "LotteryWallet/Data/V2/GeneratedLotteryReadKey.swift"
    target.write_text(
        "// Generated by Scripts/write-api-config.py. Never commit this file.\n"
        "enum GeneratedLotteryReadKey {\n"
        f"    static let value: String? = {value}\n"
        "}\n"
    )
    target.chmod(0o600)
    print("App read key configured." if key else "No App read key: CloudBase rejection will use the GitHub fallback.")


if __name__ == "__main__":
    main()
